apiVersion: v1
kind: Service
metadata:
  name: { { include "channelfinder.fullname" . } }
spec:
  type: { { .Values.service.type } }
  ports:
    - port: { { .Values.service.port } }
      targetPort: { { .Values.service.port } }
  selector:
    app: { { include "channelfinder.name" . } }

---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-cf
spec:
  type: ClusterIP
  ports:
    - port: { { .Values.elasticsearchService.port } }
      targetPort: { { .Values.elasticsearchService.port } }
  selector:
    app: elasticsearch-cf
